version: '3.7'

services:
  agent-live-eta:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    volumes:
      - ./src:/src:rw,consistent
      - ./vendor:/vendor:rw,consistent
      - ./tests:/tests:rw,consistent
      - ./Makefile:/Makefile:rw,consistent
    container_name: spia-agent-live-eta
    env_file: .env

volumes:
  src:
  vendor: